// GENERATED by `supabase generate_typescript_types` against project
// eubadixqqwwfoennlaez (pakangers-tournament). Do not hand-edit -- regenerate
// after every migration instead.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_ip: string | null
          actor_name: string
          after: Json | null
          before: Json | null
          created_at: string
          entity_id: string
          entity_type: string
          id: string
          tournament_id: string
        }
        Insert: {
          action: string
          actor_ip?: string | null
          actor_name: string
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity_id: string
          entity_type: string
          id?: string
          tournament_id: string
        }
        Update: {
          action?: string
          actor_ip?: string | null
          actor_name?: string
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity_id?: string
          entity_type?: string
          id?: string
          tournament_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournament"
            referencedColumns: ["id"]
          },
        ]
      }
      bracket_node: {
        Row: {
          away_ref: Json | null
          created_at: string
          home_ref: Json | null
          id: string
          loser_to_node_id: string | null
          match_id: string | null
          position: number
          round: number
          stage_id: string
          winner_to_node_id: string | null
        }
        Insert: {
          away_ref?: Json | null
          created_at?: string
          home_ref?: Json | null
          id?: string
          loser_to_node_id?: string | null
          match_id?: string | null
          position: number
          round: number
          stage_id: string
          winner_to_node_id?: string | null
        }
        Update: {
          away_ref?: Json | null
          created_at?: string
          home_ref?: Json | null
          id?: string
          loser_to_node_id?: string | null
          match_id?: string | null
          position?: number
          round?: number
          stage_id?: string
          winner_to_node_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bracket_node_loser_to_node_id_fkey"
            columns: ["loser_to_node_id"]
            isOneToOne: false
            referencedRelation: "bracket_node"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bracket_node_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "match"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bracket_node_stage_id_fkey"
            columns: ["stage_id"]
            isOneToOne: false
            referencedRelation: "stage"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bracket_node_winner_to_node_id_fkey"
            columns: ["winner_to_node_id"]
            isOneToOne: false
            referencedRelation: "bracket_node"
            referencedColumns: ["id"]
          },
        ]
      }
      court: {
        Row: {
          created_at: string
          id: string
          is_available: boolean
          name: string
          tournament_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_available?: boolean
          name: string
          tournament_id: string
        }
        Update: {
          created_at?: string
          id?: string
          is_available?: boolean
          name?: string
          tournament_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "court_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournament"
            referencedColumns: ["id"]
          },
        ]
      }
      division: {
        Row: {
          created_at: string
          gender_category: string | null
          id: string
          name: string
          skill_level: string | null
          team_size: number
          tournament_id: string
        }
        Insert: {
          created_at?: string
          gender_category?: string | null
          id?: string
          name: string
          skill_level?: string | null
          team_size?: number
          tournament_id: string
        }
        Update: {
          created_at?: string
          gender_category?: string | null
          id?: string
          name?: string
          skill_level?: string | null
          team_size?: number
          tournament_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "division_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournament"
            referencedColumns: ["id"]
          },
        ]
      }
      external_result_submission: {
        Row: {
          created_at: string
          error: string | null
          id: string
          match_id: string
          payload: Json | null
          provider: string
          status: string
          submitted_at: string | null
        }
        Insert: {
          created_at?: string
          error?: string | null
          id?: string
          match_id: string
          payload?: Json | null
          provider?: string
          status?: string
          submitted_at?: string | null
        }
        Update: {
          created_at?: string
          error?: string | null
          id?: string
          match_id?: string
          payload?: Json | null
          provider?: string
          status?: string
          submitted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "external_result_submission_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "match"
            referencedColumns: ["id"]
          },
        ]
      }
      game: {
        Row: {
          away_score: number
          created_at: string
          game_number: number
          home_score: number
          id: string
          match_id: string
        }
        Insert: {
          away_score: number
          created_at?: string
          game_number: number
          home_score: number
          id?: string
          match_id: string
        }
        Update: {
          away_score?: number
          created_at?: string
          game_number?: number
          home_score?: number
          id?: string
          match_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "game_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: false
            referencedRelation: "match"
            referencedColumns: ["id"]
          },
        ]
      }
      match: {
        Row: {
          away_team_id: string | null
          bracket_node_id: string | null
          court_id: string | null
          created_at: string
          group_id: string | null
          home_team_id: string | null
          id: string
          match_number: number
          scheduled_at: string | null
          scoring_config: Json
          source: string
          stage_id: string
          status: string
          supersedes_match_id: string | null
          tournament_id: string
        }
        Insert: {
          away_team_id?: string | null
          bracket_node_id?: string | null
          court_id?: string | null
          created_at?: string
          group_id?: string | null
          home_team_id?: string | null
          id?: string
          match_number: number
          scheduled_at?: string | null
          scoring_config: Json
          source?: string
          stage_id: string
          status?: string
          supersedes_match_id?: string | null
          tournament_id: string
        }
        Update: {
          away_team_id?: string | null
          bracket_node_id?: string | null
          court_id?: string | null
          created_at?: string
          group_id?: string | null
          home_team_id?: string | null
          id?: string
          match_number?: number
          scheduled_at?: string | null
          scoring_config?: Json
          source?: string
          stage_id?: string
          status?: string
          supersedes_match_id?: string | null
          tournament_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "match_away_team_id_fkey"
            columns: ["away_team_id"]
            isOneToOne: false
            referencedRelation: "team"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_bracket_node_id_fkey"
            columns: ["bracket_node_id"]
            isOneToOne: false
            referencedRelation: "bracket_node"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_court_id_fkey"
            columns: ["court_id"]
            isOneToOne: false
            referencedRelation: "court"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "tournament_group"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_home_team_id_fkey"
            columns: ["home_team_id"]
            isOneToOne: false
            referencedRelation: "team"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_stage_id_fkey"
            columns: ["stage_id"]
            isOneToOne: false
            referencedRelation: "stage"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_supersedes_match_id_fkey"
            columns: ["supersedes_match_id"]
            isOneToOne: false
            referencedRelation: "match"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournament"
            referencedColumns: ["id"]
          },
        ]
      }
      match_result: {
        Row: {
          away_games_won: number
          away_points_total: number
          home_games_won: number
          home_points_total: number
          id: string
          match_id: string
          recorded_at: string
          recorded_by: string
          result_type: string
          winner_team_id: string | null
        }
        Insert: {
          away_games_won?: number
          away_points_total?: number
          home_games_won?: number
          home_points_total?: number
          id?: string
          match_id: string
          recorded_at?: string
          recorded_by: string
          result_type?: string
          winner_team_id?: string | null
        }
        Update: {
          away_games_won?: number
          away_points_total?: number
          home_games_won?: number
          home_points_total?: number
          id?: string
          match_id?: string
          recorded_at?: string
          recorded_by?: string
          result_type?: string
          winner_team_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "match_result_match_id_fkey"
            columns: ["match_id"]
            isOneToOne: true
            referencedRelation: "match"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "match_result_winner_team_id_fkey"
            columns: ["winner_team_id"]
            isOneToOne: false
            referencedRelation: "team"
            referencedColumns: ["id"]
          },
        ]
      }
      player: {
        Row: {
          contact: string | null
          created_at: string
          dupr_id: string | null
          first_name: string
          id: string
          last_name: string
          notes: string | null
          skill_rating: number | null
          tournament_id: string
        }
        Insert: {
          contact?: string | null
          created_at?: string
          dupr_id?: string | null
          first_name: string
          id?: string
          last_name: string
          notes?: string | null
          skill_rating?: number | null
          tournament_id: string
        }
        Update: {
          contact?: string | null
          created_at?: string
          dupr_id?: string | null
          first_name?: string
          id?: string
          last_name?: string
          notes?: string | null
          skill_rating?: number | null
          tournament_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "player_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournament"
            referencedColumns: ["id"]
          },
        ]
      }
      qualification_rule: {
        Row: {
          created_at: string
          from_group_id: string | null
          from_stage_id: string
          id: string
          method: string
          seeding_policy: string | null
          to_stage_id: string
          value: number
        }
        Insert: {
          created_at?: string
          from_group_id?: string | null
          from_stage_id: string
          id?: string
          method: string
          seeding_policy?: string | null
          to_stage_id: string
          value: number
        }
        Update: {
          created_at?: string
          from_group_id?: string | null
          from_stage_id?: string
          id?: string
          method?: string
          seeding_policy?: string | null
          to_stage_id?: string
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "qualification_rule_from_group_id_fkey"
            columns: ["from_group_id"]
            isOneToOne: false
            referencedRelation: "tournament_group"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "qualification_rule_from_stage_id_fkey"
            columns: ["from_stage_id"]
            isOneToOne: false
            referencedRelation: "stage"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "qualification_rule_to_stage_id_fkey"
            columns: ["to_stage_id"]
            isOneToOne: false
            referencedRelation: "stage"
            referencedColumns: ["id"]
          },
        ]
      }
      rule_set: {
        Row: {
          created_at: string
          edition_year: number
          effective_date: string
          governing_body: string
          id: string
          name: string
          source_url: string
        }
        Insert: {
          created_at?: string
          edition_year: number
          effective_date: string
          governing_body: string
          id?: string
          name: string
          source_url: string
        }
        Update: {
          created_at?: string
          edition_year?: number
          effective_date?: string
          governing_body?: string
          id?: string
          name?: string
          source_url?: string
        }
        Relationships: []
      }
      stage: {
        Row: {
          created_at: string
          division_id: string
          entrant_config: Json
          format_key: string
          id: string
          key: string
          name: string
          scoring_config: Json
          sequence: number
          status: string
          tiebreaker_config: Json
          tournament_id: string
        }
        Insert: {
          created_at?: string
          division_id: string
          entrant_config?: Json
          format_key: string
          id?: string
          key: string
          name: string
          scoring_config?: Json
          sequence?: number
          status?: string
          tiebreaker_config?: Json
          tournament_id: string
        }
        Update: {
          created_at?: string
          division_id?: string
          entrant_config?: Json
          format_key?: string
          id?: string
          key?: string
          name?: string
          scoring_config?: Json
          sequence?: number
          status?: string
          tiebreaker_config?: Json
          tournament_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "stage_division_id_fkey"
            columns: ["division_id"]
            isOneToOne: false
            referencedRelation: "division"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stage_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournament"
            referencedColumns: ["id"]
          },
        ]
      }
      team: {
        Row: {
          created_at: string
          division_id: string
          group_id: string | null
          id: string
          locked_at: string | null
          name: string
          seed: number | null
          team_number: number | null
          tournament_id: string
        }
        Insert: {
          created_at?: string
          division_id: string
          group_id?: string | null
          id?: string
          locked_at?: string | null
          name: string
          seed?: number | null
          team_number?: number | null
          tournament_id: string
        }
        Update: {
          created_at?: string
          division_id?: string
          group_id?: string | null
          id?: string
          locked_at?: string | null
          name?: string
          seed?: number | null
          team_number?: number | null
          tournament_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "team_division_id_fkey"
            columns: ["division_id"]
            isOneToOne: false
            referencedRelation: "division"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "tournament_group"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournament"
            referencedColumns: ["id"]
          },
        ]
      }
      team_member: {
        Row: {
          player_id: string
          position: number
          team_id: string
        }
        Insert: {
          player_id: string
          position?: number
          team_id: string
        }
        Update: {
          player_id?: string
          position?: number
          team_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "team_member_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "player"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_member_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "team"
            referencedColumns: ["id"]
          },
        ]
      }
      tournament: {
        Row: {
          created_at: string
          created_from_template_id: string | null
          date_end: string | null
          date_start: string | null
          description: string | null
          id: string
          logo_url: string | null
          name: string
          organizer_name: string | null
          rule_set_id: string | null
          slug: string
          status: string
          timezone: string
          updated_at: string
          venue: string | null
        }
        Insert: {
          created_at?: string
          created_from_template_id?: string | null
          date_end?: string | null
          date_start?: string | null
          description?: string | null
          id?: string
          logo_url?: string | null
          name: string
          organizer_name?: string | null
          rule_set_id?: string | null
          slug: string
          status?: string
          timezone?: string
          updated_at?: string
          venue?: string | null
        }
        Update: {
          created_at?: string
          created_from_template_id?: string | null
          date_end?: string | null
          date_start?: string | null
          description?: string | null
          id?: string
          logo_url?: string | null
          name?: string
          organizer_name?: string | null
          rule_set_id?: string | null
          slug?: string
          status?: string
          timezone?: string
          updated_at?: string
          venue?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tournament_created_from_template_id_fkey"
            columns: ["created_from_template_id"]
            isOneToOne: false
            referencedRelation: "tournament_template"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tournament_rule_set_id_fkey"
            columns: ["rule_set_id"]
            isOneToOne: false
            referencedRelation: "rule_set"
            referencedColumns: ["id"]
          },
        ]
      }
      tournament_group: {
        Row: {
          created_at: string
          display_order: number
          id: string
          name: string
          stage_id: string
        }
        Insert: {
          created_at?: string
          display_order?: number
          id?: string
          name: string
          stage_id: string
        }
        Update: {
          created_at?: string
          display_order?: number
          id?: string
          name?: string
          stage_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tournament_group_stage_id_fkey"
            columns: ["stage_id"]
            isOneToOne: false
            referencedRelation: "stage"
            referencedColumns: ["id"]
          },
        ]
      }
      tournament_rule: {
        Row: {
          category: string
          created_at: string
          display_order: number
          id: string
          rule_set_id: string | null
          source_ref: string | null
          summary_text: string
          title: string
          tournament_id: string | null
        }
        Insert: {
          category: string
          created_at?: string
          display_order?: number
          id?: string
          rule_set_id?: string | null
          source_ref?: string | null
          summary_text: string
          title: string
          tournament_id?: string | null
        }
        Update: {
          category?: string
          created_at?: string
          display_order?: number
          id?: string
          rule_set_id?: string | null
          source_ref?: string | null
          summary_text?: string
          title?: string
          tournament_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tournament_rule_rule_set_id_fkey"
            columns: ["rule_set_id"]
            isOneToOne: false
            referencedRelation: "rule_set"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tournament_rule_tournament_id_fkey"
            columns: ["tournament_id"]
            isOneToOne: false
            referencedRelation: "tournament"
            referencedColumns: ["id"]
          },
        ]
      }
      tournament_template: {
        Row: {
          config: Json
          created_at: string
          description: string | null
          id: string
          name: string
          source_tournament_id: string | null
        }
        Insert: {
          config: Json
          created_at?: string
          description?: string | null
          id?: string
          name: string
          source_tournament_id?: string | null
        }
        Update: {
          config?: Json
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          source_tournament_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tournament_template_source_tournament_id_fkey"
            columns: ["source_tournament_id"]
            isOneToOne: false
            referencedRelation: "tournament"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
